services:
  graph-info:
    build: .
    container_name: graph_info
    environment:
      GRAPH_DATA_ENDPOINT: http://xml-server/multiple_paths_cycles.xml
#      GRAPH_DATA_ENDPOINT: http://xml-server/multiple_paths_1.xml
#      GRAPH_DATA_ENDPOINT: http://xml-server/multiple_paths_2.xml
#      GRAPH_DATA_ENDPOINT: http://xml-server/original_example.xml
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: graphs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    stdin_open: true
    tty: true
    depends_on:
      - db
      - xml-server
    networks:
      - app-network

  db:
    build:
      context: ./database
    container_name: postgres
    environment:
      POSTGRES_DB: graphs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    networks:
      - app-network

  xml-server:
    build:
      context: sample_graph_data
    container_name: xml_server
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
